'use client';

import { readProgress, type ProgressSnapshot } from '@/lib/progress';
import { useEffect, useState } from 'react';

export function ProgressDashboard() {
  const [progress, setProgress] = useState<ProgressSnapshot | null>(null);
  useEffect(() => { const refresh=()=>setProgress(readProgress()); refresh(); window.addEventListener('eduia-progress',refresh); return()=>window.removeEventListener('eduia-progress',refresh); }, []);
  if (!progress) return <div role="status" className="rounded-3xl bg-white p-8 text-[#607488] ring-1 ring-[#dcebed]">A preparar o teu progresso…</div>;
  const autonomy = progress.sessionsCompleted === 0 ? 'Ainda sem dados' : progress.hintsUsed / progress.sessionsCompleted <= 1 ? 'A trabalhar com pouca ajuda' : 'A praticar com pistas';
  const cards = [['Temas estudados',Object.keys(progress.topics).length,'▦'],['Sessões concluídas',progress.sessionsCompleted,'✓'],['Exercícios praticados',progress.exercisesPractised,'✎'],['Pistas utilizadas',progress.hintsUsed,'?']];
  return <>{progress.sessionsCompleted===0&&<div className="mb-6 rounded-3xl bg-white p-7 text-center ring-1 ring-[#dcebed]"><span className="text-4xl" aria-hidden="true">✦</span><h2 className="mt-4 text-xl font-black text-[#0E2A55]">O teu progresso começa com a primeira sessão</h2><p className="mt-2 text-[#617589]">Experimenta uma dúvida, um cartão ou uma palavra.</p></div>}<div className="grid grid-cols-2 gap-4 lg:grid-cols-4">{cards.map(([label,value,icon])=><article key={String(label)} className="rounded-3xl bg-white p-5 ring-1 ring-[#dcebed]"><span className="grid size-11 place-items-center rounded-2xl bg-[#e5f8f8] font-black text-[#0b7f81]" aria-hidden="true">{icon}</span><p className="mt-5 text-3xl font-black text-[#0E2A55]">{value}</p><h2 className="mt-1 text-sm font-bold text-[#617589]">{label}</h2></article>)}</div><section className="mt-6 grid gap-5 lg:grid-cols-2"><article className="rounded-3xl bg-[#0E2A55] p-7 text-white"><p className="text-sm font-bold uppercase tracking-[.12em] text-[#8fe4e2]">Autonomia</p><h2 className="mt-3 text-2xl font-black">{autonomy}</h2><p className="mt-3 leading-7 text-[#d6e7f2]">O objetivo é precisares cada vez menos de pistas. Não há comparações nem sequências para manter.</p></article><article className="rounded-3xl bg-white p-7 ring-1 ring-[#dcebed]"><p className="text-sm font-bold uppercase tracking-[.12em] text-[#0b7f81]">Áreas revistas</p>{Object.keys(progress.topics).length===0?<p className="mt-4 text-[#617589]">Ainda não escolheste áreas para rever.</p>:<ul className="mt-4 space-y-3">{Object.entries(progress.topics).map(([topic,count])=><li key={topic} className="flex justify-between rounded-2xl bg-[#f2f9fa] px-4 py-3 font-semibold text-[#2f485e]"><span>{topic}</span><span>{count}</span></li>)}</ul>}</article></section></>;
}
