import Link from 'next/link';
import Image from 'next/image';

export default function LandingPage() {
  return <main className="min-h-screen overflow-hidden bg-[#F7FBFC] text-[#12243C]">
    <header className="mx-auto flex max-w-7xl items-center justify-between px-5 py-6 sm:px-8"><Image src="/eduia-logo.svg" alt="EduIA" width={420} height={120} className="h-auto w-40 sm:w-48" priority /><Link href="/entrar" className="rounded-2xl border border-[#b8dfe2] bg-white px-5 py-3 font-extrabold text-[#0E2A55] shadow-sm focus-visible:outline focus-visible:outline-4 focus-visible:outline-[#18B9B7]">Entrar</Link></header>
    <section className="mx-auto grid max-w-7xl items-center gap-12 px-5 py-12 sm:px-8 md:grid-cols-[1.1fr_.9fr] md:py-24">
      <div><p className="text-sm font-extrabold uppercase tracking-[.14em] text-[#0b7f81]">O teu companheiro de aprendizagem</p><h1 className="mt-4 max-w-3xl text-5xl font-black leading-[1.03] tracking-[-.05em] text-[#0E2A55] sm:text-6xl lg:text-7xl">Aprender melhor,<br /><span className="text-[#0B7F81]">com mais autonomia.</span></h1><p className="mt-7 max-w-2xl text-lg leading-8 text-[#52677c]">O EduIA ajuda-te a compreender, experimentar e corrigir. Dá-te pistas para encontrares o caminho — sem fazer o trabalho por ti.</p><div className="mt-9 flex flex-wrap gap-4"><Link href="/entrar" className="rounded-2xl bg-[#0E2A55] px-6 py-4 font-extrabold text-white shadow-lg shadow-[#0E2A55]/15 transition hover:-translate-y-0.5 focus-visible:outline focus-visible:outline-4 focus-visible:outline-offset-2 focus-visible:outline-[#18B9B7]">Começar agora <span aria-hidden="true">→</span></Link><a href="#como-funciona" className="rounded-2xl bg-white px-6 py-4 font-extrabold text-[#0E2A55] ring-1 ring-[#cfe3e6] focus-visible:outline focus-visible:outline-4 focus-visible:outline-[#18B9B7]">Ver como funciona</a></div></div>
      <div className="relative mx-auto w-full max-w-lg"><div className="absolute -inset-8 rounded-full bg-[#3FC4D6]/10 blur-3xl" /><div className="relative rounded-[42px] bg-[#0E2A55] p-8 shadow-[0_30px_90px_rgba(14,42,85,.2)]"><div className="mx-auto grid size-40 place-items-center rounded-[50px] border-[7px] border-[#18B9B7] bg-[#F7FBFC]"><div className="grid h-20 w-28 place-items-center rounded-[32px] bg-[#0E2A55] text-4xl text-[#7EE4E1]">⌒‿⌒</div></div><div className="mt-8 rounded-3xl bg-white p-6"><p className="font-extrabold text-[#0E2A55]">“Vamos olhar para este passo.”</p><p className="mt-2 text-sm leading-6 text-[#5c7185]">Como chegaste ao teu resultado?</p><div className="mt-5 h-3 w-4/5 rounded-full bg-[#dff5f6]" /><div className="mt-2 h-3 w-3/5 rounded-full bg-[#edf5f6]" /></div></div></div>
    </section>
    <section id="como-funciona" className="mx-auto max-w-7xl px-5 pb-24 sm:px-8"><div className="grid gap-4 md:grid-cols-3">{[['1','Tu tentas','Conta o que sabes e mostra o teu raciocínio.'],['2','Recebes uma pista','O EduIA ajuda com uma ideia de cada vez.'],['3','Compreendes','Explicas o que aprendeste e praticas novamente.']].map(([n,title,text])=><article key={n} className="rounded-3xl bg-white p-7 ring-1 ring-[#dcebed]"><span className="grid size-10 place-items-center rounded-full bg-[#18B9B7] font-black text-white">{n}</span><h2 className="mt-5 text-xl font-black text-[#0E2A55]">{title}</h2><p className="mt-2 leading-7 text-[#5b7084]">{text}</p></article>)}</div></section>
  </main>;
}
